name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  validate_syllabus:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v1
    - name: Get PR Branch Name
      run: echo ${{ github.head_ref }}
    - name: Force Fail
      run: exit -1
